# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/paulo.duarte/Documents/GitKraken/JSON-Scrip

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/paulo.duarte/Documents/GitKraken/JSON-Scrip

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/paulo.duarte/Documents/GitKraken/JSON-Scrip/CMakeFiles /mnt/c/Users/paulo.duarte/Documents/GitKraken/JSON-Scrip/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/paulo.duarte/Documents/GitKraken/JSON-Scrip/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named script_exe

# Build rule for target.
script_exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 script_exe
.PHONY : script_exe

# fast build rule for target.
script_exe/fast:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/build
.PHONY : script_exe/fast

src/comum.o: src/comum.cpp.o

.PHONY : src/comum.o

# target to build an object file
src/comum.cpp.o:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/comum.cpp.o
.PHONY : src/comum.cpp.o

src/comum.i: src/comum.cpp.i

.PHONY : src/comum.i

# target to preprocess a source file
src/comum.cpp.i:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/comum.cpp.i
.PHONY : src/comum.cpp.i

src/comum.s: src/comum.cpp.s

.PHONY : src/comum.s

# target to generate assembly for a file
src/comum.cpp.s:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/comum.cpp.s
.PHONY : src/comum.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/matriz_pontos.o: src/matriz_pontos.cpp.o

.PHONY : src/matriz_pontos.o

# target to build an object file
src/matriz_pontos.cpp.o:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/matriz_pontos.cpp.o
.PHONY : src/matriz_pontos.cpp.o

src/matriz_pontos.i: src/matriz_pontos.cpp.i

.PHONY : src/matriz_pontos.i

# target to preprocess a source file
src/matriz_pontos.cpp.i:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/matriz_pontos.cpp.i
.PHONY : src/matriz_pontos.cpp.i

src/matriz_pontos.s: src/matriz_pontos.cpp.s

.PHONY : src/matriz_pontos.s

# target to generate assembly for a file
src/matriz_pontos.cpp.s:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/matriz_pontos.cpp.s
.PHONY : src/matriz_pontos.cpp.s

src/simulacao.o: src/simulacao.cpp.o

.PHONY : src/simulacao.o

# target to build an object file
src/simulacao.cpp.o:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/simulacao.cpp.o
.PHONY : src/simulacao.cpp.o

src/simulacao.i: src/simulacao.cpp.i

.PHONY : src/simulacao.i

# target to preprocess a source file
src/simulacao.cpp.i:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/simulacao.cpp.i
.PHONY : src/simulacao.cpp.i

src/simulacao.s: src/simulacao.cpp.s

.PHONY : src/simulacao.s

# target to generate assembly for a file
src/simulacao.cpp.s:
	$(MAKE) -f CMakeFiles/script_exe.dir/build.make CMakeFiles/script_exe.dir/src/simulacao.cpp.s
.PHONY : src/simulacao.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... run"
	@echo "... script_exe"
	@echo "... src/comum.o"
	@echo "... src/comum.i"
	@echo "... src/comum.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/matriz_pontos.o"
	@echo "... src/matriz_pontos.i"
	@echo "... src/matriz_pontos.s"
	@echo "... src/simulacao.o"
	@echo "... src/simulacao.i"
	@echo "... src/simulacao.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

